modkey = "Mod4"
mousekey = "Mod1"
workspaces = []
tags = ["I", "II", "III", "4:>_", "5:snd", "6:meet", "7:chat", "8:code", "9:web"]

focus_behaviour = "Sloppy"

layouts = [
    "MainAndVertStack",
    "MainAndHorizontalStack",
]

[[scratchpad]]
name = "st"
value = "st"

[[keybind]]
command = "ToggleScratchPad"
value = "st"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = ["modkey"]
key = "d"

[[keybind]]
command = "Execute"
value = "st"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "brave"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "Execute"
value = "st -e stub"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "Execute"
value = "discord"
modifier = ["modkey", "Shift"]
key = "d"

[[keybind]]
command = "Execute"
value = "bookmarks2"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "Execute"
value = "flameshot gui"
modifier = ["modkey", "Shift"]
key = "p"

[[keybind]]
command = "Execute"
value = "passmenu --type"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "pavucontrol"
modifier = ["modkey", "Shift"]
key = "v"

[[keybind]]
command = "Execute"
value = "st -e alsamixer"
modifier = ["modkey"]
key = "v"

[[keybind]]
command = "Execute"
value = "st -e ranger"
modifier = ["modkey"]
key = "e"

[[keybind]]
command = "Execute"
value = "st -e ncmpcpp"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "Execute"
value = "pulseaudio-ctl mute"
modifier = []
key = "XF86XK_AudioMute"

[[keybind]]
command = "Execute"
value = "pulseaudio-ctl up"
modifier = []
key = "XF86XK_AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "pulseaudio-ctl down"
modifier = []
key = "XF86XK_AudioLowerVolume"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "pkill leftwm"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "Execute"
value = "locker"
modifier = ["modkey", "Shift"]
key = "l"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "t"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "t"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"
